### ISSUE TITLE
meson 0.54 breaks g-ir-scanner

### ISSUE THREAD

**Issue by pkgw** [conda-forge/meson-feedstock#30]
As per conda-forge/atk-feedstock#14:

> This looks like the change that does it: mesonbuild/meson@f66b04b.
> 
> The problem is that the build tries to call g-ir-scanner directly, but that fails because it is a python script. Previously, meson would set up the build so that it called the python executable to run g-ir-scanner. It now seems to prefer to get the entire command for running g-ir-scanner from pkg-config which just points to the path.
> 
> The proper fix seems like it belongs upstream in meson, or perhaps in gobject-introspection, but the easiest workaround would be to stick to using meson=0.53.2 for now.

CC @ryanvolz.

**Comment by tschoonj** [comment]
This can be closed right?

**Comment by pkgw** [comment]
I'm pretty sure? We can always reopen or refile if needed ...
